using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AssetTrackingSystem.Models
{
    public class SoftwareAsset
    {
        public int SoftwareAssetId { get; set; }   // Auto-generated by DB
        public string OperatingSystem { get; set; }
        public string Version { get; set; }
        public string Manufacturer { get; set; }

        // Link to hardware
        public int AssetId { get; set; }            // Hardware Asset ID
        public DateTime LinkedDate { get; set; }    // Auto-recorded
    }
}

